@id = df3f30e8-6c79-4409-a656-ba5e38283553

PUT http://localhost:5062/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Carlos Rodriguez",
  "description": "Vegan everything! Join us for a healthy breakfast.",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal",
    "Avocado Toast",
    "Omelette",
    "Salad"
  ],
  "sweet": [
    "Cookie"
  ]
}