@id = 162dc825-a2ac-406a-9a70-21e9cfc67a4e

PUT https://localhost:7284/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Carlos Rodriguez",
  "description": "Vegan everything! Join us for a healthy breakfast.",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal",
    "Avocado Toast",
    "Omelette",
    "Salad"
  ],
  "sweet": [
    "Cookie"
  ]
}